import './globals.css'
import { Baloo_Bhai_2 } from 'next/font/google'

const baloo = Baloo_Bhai_2({
   subsets: ['latin'] ,
  weight:['400', '500' , '600' , '700' , '800'],
  display: "swap",
  })

export const metadata = {
  title: ' Mohit Yadav portfolio',
  description: 'Generated by Mohit Yadav',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={baloo.className}>{children}</body>
    </html>
  )
}
